name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl, gd, xml, zip
        
    - name: Validate PHP syntax
      run: find app/public/wp-content/themes/toneka-theme -name "*.php" -exec php -l {} \;
      
    - name: Deploy to production server
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USERNAME }}
        password: ${{ secrets.PROD_PASSWORD }}
        port: ${{ secrets.PROD_PORT }}
        script: |
          # Navigate to website directory
          cd ${{ secrets.PROD_PATH }}
          
          # Create backup of current theme (if exists)
          if [ -d "wp-content/themes/toneka-theme" ]; then
            cp -r wp-content/themes/toneka-theme wp-content/themes/toneka-theme-backup-$(date +%Y%m%d-%H%M%S)
          fi
          
          # Clone or update repository
          if [ ! -d "temp-deployment" ]; then
            git clone https://github.com/jeden-/toneka_theme.git temp-deployment
          else
            cd temp-deployment
            git fetch origin main
            git reset --hard origin/main
            cd ..
          fi
          
          # Copy theme files
          cp -r temp-deployment/app/public/wp-content/themes/toneka-theme wp-content/themes/
          
          # Set correct permissions
          chmod -R 755 wp-content/themes/toneka-theme/
          
          # Clean up
          rm -rf temp-deployment
          
          echo "Deployment completed successfully!"
          
    - name: Notify deployment status
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#deployments'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
