name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl, gd, xml, zip
        
    - name: Validate PHP syntax
      run: find app/public/wp-content/themes/toneka-theme -name "*.php" -exec php -l {} \;
      
    - name: Deploy to production server
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USERNAME }}
        password: ${{ secrets.PROD_PASSWORD }}
        port: 22
        timeout: 60s
        command_timeout: 120s
        script: |
          set -e  # Exit on any error
          echo "Starting deployment..."
          
          # Navigate to website directory
          cd ${{ secrets.PROD_PATH }} || exit 1
          echo "Current directory: $(pwd)"
          
          # Create backup of current theme (if exists)
          if [ -d "wp-content/themes/toneka-theme" ]; then
            echo "Creating backup..."
            cp -r wp-content/themes/toneka-theme wp-content/themes/toneka-theme-backup-$(date +%Y%m%d-%H%M%S) || echo "Backup failed, continuing..."
          fi
          
          # Clean up any previous deployment
          rm -rf temp-deployment-toneka
          
          # Clone repository with timeout
          echo "Cloning repository..."
          timeout 60 git clone https://github.com/jeden-/toneka_theme.git temp-deployment-toneka || exit 1
          
          # Verify theme exists in repo
          if [ ! -d "temp-deployment-toneka/app/public/wp-content/themes/toneka-theme" ]; then
            echo "ERROR: Theme directory not found in repository!"
            exit 1
          fi
          
          # Copy theme files
          echo "Copying theme files..."
          cp -r temp-deployment-toneka/app/public/wp-content/themes/toneka-theme wp-content/themes/ || exit 1
          
          # Set correct permissions
          echo "Setting permissions..."
          chmod -R 755 wp-content/themes/toneka-theme/ || echo "Permission setting failed, continuing..."
          
          # Verify installation
          if [ -f "wp-content/themes/toneka-theme/style.css" ]; then
            echo "✅ Theme installed successfully!"
            echo "Files: $(find wp-content/themes/toneka-theme -type f | wc -l)"
          else
            echo "❌ Theme installation failed!"
            exit 1
          fi
          
          # Clean up
          rm -rf temp-deployment-toneka
          
          echo "🚀 Deployment completed successfully!"
